import 'package:flutter/material.dart';

import '../../../core/localization/l10n.dart';
import '../../../shared/widgets/empty_list_screen.dart';

/// Weekly and monthly reports, CSV export (spec 4.10). Managers and admins.
///
/// NOT IMPLEMENTED (Sprint 6): generated by Cloud Functions.
class ReportsScreen extends StatelessWidget {
  const ReportsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    return EmptyListScreen(
      title: l10n.reportsTitle,
      icon: Icons.summarize_outlined,
      emptyTitle: l10n.reportsEmptyTitle,
      emptyMessage: l10n.reportsEmptyMessage,
    );
  }
}
